"""add updated_at

Revision ID: 8fe245684657
Revises: dd109289d1e4
Create Date: 2026-05-21 11:44:18.036539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8fe245684657'
down_revision: Union[str, Sequence[str], None] = 'dd109289d1e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'published_date',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_unique_constraint(None, 'books', ['uid'])
    op.add_column('user_accounts', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    op.create_unique_constraint(None, 'user_accounts', ['username'])
    op.create_unique_constraint(None, 'user_accounts', ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_accounts', type_='unique')
    op.drop_constraint(None, 'user_accounts', type_='unique')
    op.drop_column('user_accounts', 'updated_at')
    op.drop_constraint(None, 'books', type_='unique')
    op.alter_column('books', 'published_date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
