from fastapi import FastAPI, status
from fastapi.requests import Request
from fastapi.responses import JSONResponse
from fastapi.middleware.cors import CORSMiddleware
from starlette.middleware.trustedhost import TrustedHostMiddleware
import time
import logging

from httpx import request

logger = logging.getLogger("uvicorn.access")
logger.disabled = True

def register_middleware(app: FastAPI):
    @app.middleware("http")
    async def custom_logging(request: Request, call_next):
        start_time = time.time()

        response = await call_next(request)
        processing_time = time.time() - start_time

        message = f"{request.client.host}:{request.client.port} - {request.method} - {request.url.path} - {response.status_code} completed after {processing_time}s"
        print(message)

        return response
    
    app.add_middleware(
        CORSMiddleware,
        allow_origins=["*"],
        allow_methods=["*"],
        allow_headers=["*"],
        allow_credentials=True,
    )

    app.add_middleware(
        TrustedHostMiddleware,
        allowed_hosts=["localhost","127.0.0.1"],
    )



    # middleware flow of execution:
    # 1. The custom_logging middleware is executed first, logging the incoming request and measuring the processing time.
    # 2. The request is then passed to the next middleware or route handler using call_next(request).
    # 3. After the response is generated by the route handler, the custom_logging middleware logs the response details and the time taken to process the request.
    # 4. The CORSMiddleware is executed next, handling Cross-Origin Resource Sharing (CORS) policies for the request.
    # 5. Finally, the TrustedHostMiddleware is executed, ensuring that the request is coming  from an allowed host before the request is processed further.



    #     Multiple middleware execution order¶
    # When you add multiple middlewares using   either @app.middleware() decorator or app.    add_middleware() method, each new middleware    wraps the application, forming a stack. The    last middleware added is the outermost, and    the first is the innermost.
    
    # On the request path, the outermost    middleware runs first.
    
    # On the response path, it runs last.
    
    # For example:
    
    
    # app.add_middleware(MiddlewareA)
    # app.add_middleware(MiddlewareB)
    # This results in the following execution   order:
    
    # Request: MiddlewareB → MiddlewareA → route
    
    # Response: route → MiddlewareA → MiddlewareB
    
    # This stacking behavior ensures that   middlewares are executed in a predictable and     controllable order.